name: First Workflow

on:
  - push

jobs: 
    first_job:
        name: jomacs-k8s 
        runs-on: ubuntu-latest
        steps:
            - name: First Message
              run: echo "Welcome to the world of CICI through GitHub Actions"

            - name: List All Files includding hidden 
              run: ls -1a

            - name: Show Present working Directory
              run: pwd